AWSTemplateFormatVersion: '2010-09-09'
Description: Redshift with public networking for Power BI access

Parameters:
  MasterUsername:
    Description: Redshift Master Username
    Type: String
    Default: dspadmin
  MasterUserPassword:
    Description: Redshift Master User Password
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 64

Resources:

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: PowerBI-VPC

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: PowerBI-Public-Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  RedshiftSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Redshift access from Power BI
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Open to public for Power BI access (use caution)

  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Subnet group for Redshift in public subnet
      SubnetIds:
        - !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: RedshiftSubnetGroup

  RedshiftRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: redshift-access-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: powerbi-redshift-cluster
      DBName: powerbidb
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: ra3.large
      ClusterType: single-node
      PubliclyAccessible: true
      IamRoles:
        - !GetAtt RedshiftRole.Arn
      VpcSecurityGroupIds:
        - !Ref RedshiftSG
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup

Outputs:
  RedshiftEndpoint:
    Description: Redshift endpoint for Power BI
    Value: !GetAtt RedshiftCluster.Endpoint.Address
  RedshiftPort:
    Description: Port for Redshift (default 5439)
    Value: !GetAtt RedshiftCluster.Endpoint.Port